# Basic Dataset Inspection

In [1]:
import pandas as pd
import os

In [3]:
import pandas as pd

df = pd.read_csv(
    r"D:\aiLAB99\Customer-Personality-Analysis\01_Raw_Data\marketing_campaign.csv",
    sep="\t"
)

print(df.head())

     ID  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0  5524        1957  Graduation         Single  58138.0        0         0
1  2174        1954  Graduation         Single  46344.0        1         1
2  4141        1965  Graduation       Together  71613.0        0         0
3  6182        1984  Graduation       Together  26646.0        1         0
4  5324        1981         PhD        Married  58293.0        1         0

  Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
0  04-09-2012       58       635  ...                  7             0
1  08-03-2014       38        11  ...                  5             0
2  21-08-2013       26       426  ...                  4             0
3  10-02-2014       26        11  ...                  6             0
4  19-01-2014       94       173  ...                  5             0

   AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0             0             0             0             0         0
1             0             0             0             0         0
2             0             0             0             0         0
3             0             0             0             0         0
4             0             0             0             0         0

   Z_CostContact  Z_Revenue  Response
0              3         11         1
1              3         11         0
2              3         11         0
3              3         11         0
4              3         11         0

[5 rows x 29 columns]

# Number of Rows and Columns

In [6]:
df.shape

(2240, 29)

In [7]:
rows, columns = df.shape
print("Rows:", rows)
print("Columns:", columns)

Rows: 2240
Columns: 29

# Display column names

In [8]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='str')

# Dataset Information

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 507.6 KB

# File Size

In [10]:
import os

file_path = r"D:\aiLAB99\Customer-Personality-Analysis\01_Raw_Data\marketing_campaign.csv"

size = os.path.getsize(file_path)

print(f"Dataset Size: {size/1024:.2f} KB")

Dataset Size: 215.03 KB

# Numerical Summary

In [11]:
df.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

# Check file encoding

In [12]:
import chardet

with open(file_path, "rb") as f:
    print(chardet.detect(f.read()))

{'encoding': 'ascii', 'confidence': 1.0, 'language': 'en', 'mime_type': 'text/plain'}

#  Variable Inspection

## Objective
The objective of this task is to inspect every variable in the dataset, identify its data type, understand its purpose, and record an example value for documentation.

In [13]:
# Display all column names
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='str')

In [14]:
# Display data type of each variable
df.dtypes

ID                       int64
Year_Birth               int64
Education                  str
Marital_Status             str
Income                 float64
Kidhome                  int64
Teenhome                 int64
Dt_Customer                str
Recency                  int64
MntWines                 int64
MntFruits                int64
MntMeatProducts          int64
MntFishProducts          int64
MntSweetProducts         int64
MntGoldProds             int64
NumDealsPurchases        int64
NumWebPurchases          int64
NumCatalogPurchases      int64
NumStorePurchases        int64
NumWebVisitsMonth        int64
AcceptedCmp3             int64
AcceptedCmp4             int64
AcceptedCmp5             int64
AcceptedCmp1             int64
AcceptedCmp2             int64
Complain                 int64
Z_CostContact            int64
Z_Revenue                int64
Response                 int64
dtype: object

In [15]:
# Display the first customer record
df.iloc[0]

ID                           5524
Year_Birth                   1957
Education              Graduation
Marital_Status             Single
Income                    58138.0
Kidhome                         0
Teenhome                        0
Dt_Customer            04-09-2012
Recency                        58
MntWines                      635
MntFruits                      88
MntMeatProducts               546
MntFishProducts               172
MntSweetProducts               88
MntGoldProds                   88
NumDealsPurchases               3
NumWebPurchases                 8
NumCatalogPurchases            10
NumStorePurchases               4
NumWebVisitsMonth               7
AcceptedCmp3                    0
AcceptedCmp4                    0
AcceptedCmp5                    0
AcceptedCmp1                    0
AcceptedCmp2                    0
Complain                        0
Z_CostContact                   3
Z_Revenue                      11
Response                        1
Name: 0, dtype: object

# Task 5: Identify Missing Values

## Objective
The objective of this task is to identify missing values in the dataset and calculate the percentage of missing values for each variable.

In [4]:
# Missing values in each column
missing_values = df.isnull().sum()

missing_values

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [5]:
# Percentage of missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

ID                     0.000000
Year_Birth             0.000000
Education              0.000000
Marital_Status         0.000000
Income                 1.071429
Kidhome                0.000000
Teenhome               0.000000
Dt_Customer            0.000000
Recency                0.000000
MntWines               0.000000
MntFruits              0.000000
MntMeatProducts        0.000000
MntFishProducts        0.000000
MntSweetProducts       0.000000
MntGoldProds           0.000000
NumDealsPurchases      0.000000
NumWebPurchases        0.000000
NumCatalogPurchases    0.000000
NumStorePurchases      0.000000
NumWebVisitsMonth      0.000000
AcceptedCmp3           0.000000
AcceptedCmp4           0.000000
AcceptedCmp5           0.000000
AcceptedCmp1           0.000000
AcceptedCmp2           0.000000
Complain               0.000000
Z_CostContact          0.000000
Z_Revenue              0.000000
Response               0.000000
dtype: float64

In [6]:
# Create a missing values summary table
missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_report

                     Missing Values  Percentage
ID                                0    0.000000
Year_Birth                        0    0.000000
Education                         0    0.000000
Marital_Status                    0    0.000000
Income                           24    1.071429
Kidhome                           0    0.000000
Teenhome                          0    0.000000
Dt_Customer                       0    0.000000
Recency                           0    0.000000
MntWines                          0    0.000000
MntFruits                         0    0.000000
MntMeatProducts                   0    0.000000
MntFishProducts                   0    0.000000
MntSweetProducts                  0    0.000000
MntGoldProds                      0    0.000000
NumDealsPurchases                 0    0.000000
NumWebPurchases                   0    0.000000
NumCatalogPurchases               0    0.000000
NumStorePurchases                 0    0.000000
NumWebVisitsMonth                 0    0.000000
AcceptedCmp3                      0    0.000000
AcceptedCmp4                      0    0.000000
AcceptedCmp5                      0    0.000000
AcceptedCmp1                      0    0.000000
AcceptedCmp2                      0    0.000000
Complain                          0    0.000000
Z_CostContact                     0    0.000000
Z_Revenue                         0    0.000000
Response                          0    0.000000

In [7]:
# Columns without missing values
no_missing = df.columns[df.isnull().sum() == 0]

print(no_missing)

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

# Task 6: Identify Duplicate Records

## Objective
The objective of this task is to identify duplicate rows and duplicate customer IDs in the Customer Personality Analysis dataset.

In [8]:
# Count duplicate rows
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 0

In [9]:
# Count duplicate customer IDs
duplicate_ids = df["ID"].duplicated().sum()

print("Duplicate Customer IDs:", duplicate_ids)

Duplicate Customer IDs: 0

In [10]:
# Display duplicate rows
df[df.duplicated()]

Empty DataFrame
Columns: [ID, Year_Birth, Education, Marital_Status, Income, Kidhome, Teenhome, Dt_Customer, Recency, MntWines, MntFruits, MntMeatProducts, MntFishProducts, MntSweetProducts, MntGoldProds, NumDealsPurchases, NumWebPurchases, NumCatalogPurchases, NumStorePurchases, NumWebVisitsMonth, AcceptedCmp3, AcceptedCmp4, AcceptedCmp5, AcceptedCmp1, AcceptedCmp2, Complain, Z_CostContact, Z_Revenue, Response]
Index: []

[0 rows x 29 columns]

# Task 7: Identify Incorrect or Inconsistent Values

## Objective

The objective of this task is to identify incorrect, invalid, or inconsistent values in the Customer Personality Analysis dataset before preprocessing.

### Check Invalid Ages

In [11]:
from datetime import datetime

current_year = datetime.now().year

df["Age"] = current_year - df["Year_Birth"]

df["Age"].describe()

count    2240.000000
mean       57.194196
std        11.984069
min        30.000000
25%        49.000000
50%        56.000000
75%        67.000000
max       133.000000
Name: Age, dtype: float64

### check unrealistic ages

In [12]:
invalid_age = df[(df["Age"] < 18) | (df["Age"] > 100)]

print("Invalid Age Records:", len(invalid_age))

invalid_age

Invalid Age Records: 3

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age
192,7829,1900,2n Cycle,Divorced,36640.0,1,0,26-09-2013,99,15,...,0,0,0,0,0,1,3,11,0,126
239,11004,1893,2n Cycle,Single,60182.0,0,1,17-05-2014,23,8,...,0,0,0,0,0,0,3,11,0,133
339,1150,1899,PhD,Together,83532.0,0,0,26-09-2013,36,755,...,0,0,1,0,0,0,3,11,0,127

### Check Negative Income

In [13]:
negative_income = df[df["Income"] < 0]

print("Negative Income Records:", len(negative_income))

negative_income

Negative Income Records: 0

Empty DataFrame
Columns: [ID, Year_Birth, Education, Marital_Status, Income, Kidhome, Teenhome, Dt_Customer, Recency, MntWines, MntFruits, MntMeatProducts, MntFishProducts, MntSweetProducts, MntGoldProds, NumDealsPurchases, NumWebPurchases, NumCatalogPurchases, NumStorePurchases, NumWebVisitsMonth, AcceptedCmp3, AcceptedCmp4, AcceptedCmp5, AcceptedCmp1, AcceptedCmp2, Complain, Z_CostContact, Z_Revenue, Response, Age]
Index: []

[0 rows x 30 columns]

### Check Empty Values in Categorical Columns

In [14]:
categorical_columns = ["Education", "Marital_Status"]

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].value_counts(dropna=False))

Education
Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

Marital_Status
Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

### Check Date Format

In [15]:
df["Dt_Customer"] = pd.to_datetime(
    df["Dt_Customer"],
    format="%d-%m-%Y",
    errors="coerce"
)

print("Invalid Dates:", df["Dt_Customer"].isnull().sum())

Invalid Dates: 0

# Task 8: Review Numerical Variables

## Objective

The objective of this task is to identify all numerical variables and review their statistical properties such as minimum, maximum, and mean values.

In [16]:
# Select all numerical columns
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

print("Numerical Variables:")
print(numerical_columns)

Numerical Variables:
Index(['ID', 'Year_Birth', 'Income', 'Kidhome', 'Teenhome', 'Recency',
       'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts',
       'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
       'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases',
       'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5',
       'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Z_CostContact',
       'Z_Revenue', 'Response', 'Age'],
      dtype='object')

In [17]:
# Generate summary statistics
df[numerical_columns].describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107,57.194196
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274,11.984069
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,30.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,49.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,56.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,67.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000,133.000000

In [18]:
# Create a summary table
numerical_summary = pd.DataFrame({
    "Minimum": df[numerical_columns].min(),
    "Maximum": df[numerical_columns].max(),
    "Mean": df[numerical_columns].mean().round(2)
})

numerical_summary

                     Minimum   Maximum      Mean
ID                       0.0   11191.0   5592.16
Year_Birth            1893.0    1996.0   1968.81
Income                1730.0  666666.0  52247.25
Kidhome                  0.0       2.0      0.44
Teenhome                 0.0       2.0      0.51
Recency                  0.0      99.0     49.11
MntWines                 0.0    1493.0    303.94
MntFruits                0.0     199.0     26.30
MntMeatProducts          0.0    1725.0    166.95
MntFishProducts          0.0     259.0     37.53
MntSweetProducts         0.0     263.0     27.06
MntGoldProds             0.0     362.0     44.02
NumDealsPurchases        0.0      15.0      2.33
NumWebPurchases          0.0      27.0      4.08
NumCatalogPurchases      0.0      28.0      2.66
NumStorePurchases        0.0      13.0      5.79
NumWebVisitsMonth        0.0      20.0      5.32
AcceptedCmp3             0.0       1.0      0.07
AcceptedCmp4             0.0       1.0      0.07
AcceptedCmp5             0.0       1.0      0.07
AcceptedCmp1             0.0       1.0      0.06
AcceptedCmp2             0.0       1.0      0.01
Complain                 0.0       1.0      0.01
Z_CostContact            3.0       3.0      3.00
Z_Revenue               11.0      11.0     11.00
Response                 0.0       1.0      0.15
Age                     30.0     133.0     57.19

# Task 9: Review Categorical Variables

## Objective

The objective of this task is to identify all categorical variables in the dataset and examine their categories before preprocessing.

In [19]:
# Identify categorical columns
categorical_columns = df.select_dtypes(include=["object"]).columns

print("Categorical Variables:")
print(categorical_columns)

Categorical Variables:
Index(['Education', 'Marital_Status'], dtype='object')

In [20]:
# Number of categories and category names
for column in categorical_columns:
    print("=" * 50)
    print(f"Variable: {column}")
    print(f"Number of Categories: {df[column].nunique()}")
    print("Categories:")
    print(df[column].unique())
    print()

==================================================
Variable: Education
Number of Categories: 5
Categories:
['Graduation' 'PhD' 'Master' 'Basic' '2n Cycle']

==================================================
Variable: Marital_Status
Number of Categories: 8
Categories:
['Single' 'Together' 'Married' 'Divorced' 'Widow' 'Alone' 'Absurd' 'YOLO']

In [21]:
categorical_summary = pd.DataFrame({
    "Variable": categorical_columns,
    "Number of Categories": [df[col].nunique() for col in categorical_columns],
    "Categories": [", ".join(map(str, df[col].unique())) for col in categorical_columns]
})

categorical_summary

,Variable,Number of Categories,Categories
0,Education,5,"Graduation, PhD, Master, Basic, 2n Cycle"
1,Marital_Status,8,"Single, Together, Married, Divorced, Widow, Al..."

# Task 10: Business Understanding

## Objective

The objective of this task is to identify important business indicators in the Customer Personality Analysis dataset and understand how they can support marketing and customer relationship decisions.

In [22]:
# Business Indicators

business_indicators = {
    "High Income Customers": (df["Income"] > df["Income"].median()).sum(),
    "Frequent Buyers": (df["NumStorePurchases"] > df["NumStorePurchases"].median()).sum(),
    "Campaign Responders": df["Response"].sum(),
    "Customers with Complaints": df["Complain"].sum(),
    "High Website Visitors": (df["NumWebVisitsMonth"] > df["NumWebVisitsMonth"].median()).sum(),
    "High Spending Customers": (
        df["MntWines"] +
        df["MntFruits"] +
        df["MntMeatProducts"] +
        df["MntFishProducts"] +
        df["MntSweetProducts"] +
        df["MntGoldProds"]
    ).gt(
        (
            df["MntWines"] +
            df["MntFruits"] +
            df["MntMeatProducts"] +
            df["MntFishProducts"] +
            df["MntSweetProducts"] +
            df["MntGoldProds"]
        ).median()
    ).sum(),
    "Recently Active Customers": (df["Recency"] < 30).sum()
}

business_indicators

{'High Income Customers': np.int64(1108),
 'Frequent Buyers': np.int64(970),
 'Campaign Responders': np.int64(334),
 'Customers with Complaints': np.int64(21),
 'High Website Visitors': np.int64(830),
 'High Spending Customers': np.int64(1119),
 'Recently Active Customers': np.int64(692)}

In [23]:
business_summary = pd.DataFrame(
    business_indicators.items(),
    columns=["Business Indicator", "Count"]
)

business_summary

          Business Indicator  Count
0      High Income Customers   1108
1            Frequent Buyers    970
2        Campaign Responders    334
3  Customers with Complaints     21
4      High Website Visitors    830
5    High Spending Customers   1119
6  Recently Active Customers    692